// Copyright (C) 2013 Tiago Quelhas. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package sane

// #include <sane/saneopts.h>
import "C"

const (
	NAME_STANDARD             = C.SANE_NAME_STANDARD
	NAME_GEOMETRY             = C.SANE_NAME_GEOMETRY
	NAME_ENHANCEMENT          = C.SANE_NAME_ENHANCEMENT
	NAME_ADVANCED             = C.SANE_NAME_ADVANCED
	NAME_SENSORS              = C.SANE_NAME_SENSORS
	NAME_PREVIEW              = C.SANE_NAME_PREVIEW
	NAME_GRAY_PREVIEW         = C.SANE_NAME_GRAY_PREVIEW
	NAME_BIT_DEPTH            = C.SANE_NAME_BIT_DEPTH
	NAME_SCAN_MODE            = C.SANE_NAME_SCAN_MODE
	NAME_SCAN_SPEED           = C.SANE_NAME_SCAN_SPEED
	NAME_SCAN_SOURCE          = C.SANE_NAME_SCAN_SOURCE
	NAME_BACKTRACK            = C.SANE_NAME_BACKTRACK
	NAME_SCAN_TL_X            = C.SANE_NAME_SCAN_TL_X
	NAME_SCAN_TL_Y            = C.SANE_NAME_SCAN_TL_Y
	NAME_SCAN_RESOLUTION      = C.SANE_NAME_SCAN_RESOLUTION
	NAME_SCAN_X_RESOLUTION    = C.SANE_NAME_SCAN_X_RESOLUTION
	NAME_SCAN_Y_RESOLUTION    = C.SANE_NAME_SCAN_Y_RESOLUTION
	NAME_PAGE_WIDTH           = C.SANE_NAME_PAGE_WIDTH
	NAME_PAGE_HEIGHT          = C.SANE_NAME_PAGE_HEIGHT
	NAME_CUSTOM_GAMMA         = C.SANE_NAME_CUSTOM_GAMMA
	NAME_GAMMA_VECTOR         = C.SANE_NAME_GAMMA_VECTOR
	NAME_GAMMA_VECTOR_R       = C.SANE_NAME_GAMMA_VECTOR_R
	NAME_GAMMA_VECTOR_G       = C.SANE_NAME_GAMMA_VECTOR_G
	NAME_GAMMA_VECTOR_B       = C.SANE_NAME_GAMMA_VECTOR_B
	NAME_BRIGHTNESS           = C.SANE_NAME_BRIGHTNESS
	NAME_CONTRAST             = C.SANE_NAME_CONTRAST
	NAME_GRAIN_SIZE           = C.SANE_NAME_GRAIN_SIZE
	NAME_HALFTONE             = C.SANE_NAME_HALFTONE
	NAME_BLACK_LEVEL          = C.SANE_NAME_BLACK_LEVEL
	NAME_WHITE_LEVEL          = C.SANE_NAME_WHITE_LEVEL
	NAME_WHITE_LEVEL_R        = C.SANE_NAME_WHITE_LEVEL_R
	NAME_WHITE_LEVEL_G        = C.SANE_NAME_WHITE_LEVEL_G
	NAME_WHITE_LEVEL_B        = C.SANE_NAME_WHITE_LEVEL_B
	NAME_SHADOW               = C.SANE_NAME_SHADOW
	NAME_SHADOW_R             = C.SANE_NAME_SHADOW_R
	NAME_SHADOW_G             = C.SANE_NAME_SHADOW_G
	NAME_SHADOW_B             = C.SANE_NAME_SHADOW_B
	NAME_HIGHLIGHT            = C.SANE_NAME_HIGHLIGHT
	NAME_HIGHLIGHT_R          = C.SANE_NAME_HIGHLIGHT_R
	NAME_HIGHLIGHT_G          = C.SANE_NAME_HIGHLIGHT_G
	NAME_HIGHLIGHT_B          = C.SANE_NAME_HIGHLIGHT_B
	NAME_HUE                  = C.SANE_NAME_HUE
	NAME_SATURATION           = C.SANE_NAME_SATURATION
	NAME_FILE                 = C.SANE_NAME_FILE
	NAME_HALFTONE_DIMENSION   = C.SANE_NAME_HALFTONE_DIMENSION
	NAME_HALFTONE_PATTERN     = C.SANE_NAME_HALFTONE_PATTERN
	NAME_RESOLUTION_BIND      = C.SANE_NAME_RESOLUTION_BIND
	NAME_NEGATIVE             = C.SANE_NAME_NEGATIVE
	NAME_QUALITY_CAL          = C.SANE_NAME_QUALITY_CAL
	NAME_DOR                  = C.SANE_NAME_DOR
	NAME_RGB_BIND             = C.SANE_NAME_RGB_BIND
	NAME_THRESHOLD            = C.SANE_NAME_THRESHOLD
	NAME_ANALOG_GAMMA         = C.SANE_NAME_ANALOG_GAMMA
	NAME_ANALOG_GAMMA_R       = C.SANE_NAME_ANALOG_GAMMA_R
	NAME_ANALOG_GAMMA_G       = C.SANE_NAME_ANALOG_GAMMA_G
	NAME_ANALOG_GAMMA_B       = C.SANE_NAME_ANALOG_GAMMA_B
	NAME_ANALOG_GAMMA_BIND    = C.SANE_NAME_ANALOG_GAMMA_BIND
	NAME_WARMUP               = C.SANE_NAME_WARMUP
	NAME_CAL_EXPOS_TIME       = C.SANE_NAME_CAL_EXPOS_TIME
	NAME_CAL_EXPOS_TIME_R     = C.SANE_NAME_CAL_EXPOS_TIME_R
	NAME_CAL_EXPOS_TIME_G     = C.SANE_NAME_CAL_EXPOS_TIME_G
	NAME_CAL_EXPOS_TIME_B     = C.SANE_NAME_CAL_EXPOS_TIME_B
	NAME_SCAN_EXPOS_TIME      = C.SANE_NAME_SCAN_EXPOS_TIME
	NAME_SCAN_EXPOS_TIME_R    = C.SANE_NAME_SCAN_EXPOS_TIME_R
	NAME_SCAN_EXPOS_TIME_G    = C.SANE_NAME_SCAN_EXPOS_TIME_G
	NAME_SCAN_EXPOS_TIME_B    = C.SANE_NAME_SCAN_EXPOS_TIME_B
	NAME_SELECT_EXPOSURE_TIME = C.SANE_NAME_SELECT_EXPOSURE_TIME
	NAME_CAL_LAMP_DEN         = C.SANE_NAME_CAL_LAMP_DEN
	NAME_SCAN_LAMP_DEN        = C.SANE_NAME_SCAN_LAMP_DEN
	NAME_SELECT_LAMP_DENSITY  = C.SANE_NAME_SELECT_LAMP_DENSITY
	NAME_LAMP_OFF_AT_EXIT     = C.SANE_NAME_LAMP_OFF_AT_EXIT
	NAME_SCAN                 = C.SANE_NAME_SCAN
	NAME_EMAIL                = C.SANE_NAME_EMAIL
	NAME_FAX                  = C.SANE_NAME_FAX
	NAME_COPY                 = C.SANE_NAME_COPY
	NAME_CANCEL               = C.SANE_NAME_CANCEL
	NAME_PAGE_LOADED          = C.SANE_NAME_PAGE_LOADED
	NAME_COVER_OPEN           = C.SANE_NAME_COVER_OPEN
)
